<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.11">
  <POU Name="Comp02_Main" Id="{d7803cdf-0186-480a-b27a-f806155f5a0e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Comp02_Main
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Comp02_Main">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>