<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.11">
  <POU Name="Comp02_Devices" Id="{f02718e1-a717-4016-8298-7cd18f634cd0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Comp02_Devices
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Comp02_Devices">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>